export const MessagesHelper = {
  NAME_REQUIRED: 'Name is required',
  NAME_INVALID: 'Name is invalid',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Email is invalid',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_OR_EMAIL_INVALID: 'Password or email is invalid',
  PASSWORD_VALID:
    'The password must contain uppercase and lowercase letters, numbers and special characters',
  CPF_REQUIRED: 'CPF is required',
  CPF_INVALID: 'CPF is invalid',
  PHONE_REQUIRED: 'Phone is required',
  PHONE_INVALID: 'Phone is invalid',
  CODE_REQUIRED: 'Code is required',
  DESCRIPTION_REQUIRED: 'description task is required',
  DESCRIPTION_INVALID: 'description is invalid',
  CATEGORY_REQUIRED: 'category task is required',
  CATEGORY_INVALID: 'category is invalid',
  USER_ID_REQUIRED: 'user ID is required',
  TASK_ID_REQUIRED: 'task ID is required',
  TASK_ID_INVALID: 'task ID is invalid',
  PAGE_REQUIRED: 'page number is required',
  PAGE_INVALID: 'page has to be a string',
};
